import "./globals.css";
import {
  Inter,
  Carrois_Gothic,
  Heebo,
  Roboto_Condensed,
  Nova_Square,
  DM_Serif_Display,
} from "next/font/google";
import { NextAuthProvider } from "./provider";
import { AppContextProvider } from "@/context";
import { Navbar } from "@/components/navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });
const CarroisGothic = Carrois_Gothic({
  subsets: ["latin"],
  weight: "400",
  variable: "--carrois",
});
const heebo = Heebo({ subsets: ["latin"], weight: "400", variable: "--heebo" });
const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--roboto",
});
const nova = Nova_Square({
  subsets: ["latin"],
  weight: "400",
  variable: "--nova",
});
const display = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--display",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${CarroisGothic.variable} ${heebo.variable} ${roboto.variable} ${nova.variable} ${display.variable}`}
      >
        <NextAuthProvider>
          <AppContextProvider>
            <ToastContainer
              position="bottom-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
            {children}
          </AppContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
