import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./provider";
import { AppContextProvider } from "@/context";
import { Navbar } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <AppContextProvider>{children}</AppContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
